Jong en out content update
dwh-outsite/dwhdelft.nl pull request #448
Opened 2023-01-09 16:58 UTC by laurensWe

- Hidde verwijderd van de begeleiders van J&O
- Dim, Thomas, Meander, Didi & Laurens toegevoegd als J&O begeleider

2023-01-10 20:36 UTC, casperboone requested changes
Cool! Ziet er verrassend ok uit met meer dan 2 begeleiders.

De foto's zijn allemaal nog wel erg groot die mogen meer richting de 50KB. Even mensen hun databundel sparen 😛

2023-01-10 20:36 UTC, casperboone commented on sites/dwhdelft.nl/pages/jongenout.vue
> +        - 'Hey, ik ben Meander! Zelf heb ik ook mijn J&O tijd gehad, het was zo’n fijne en vertrouwde omgeving, dat wil ik daarom ook creëren voor de volgende generatie aan J&O’ers 😝!!'
```suggestion
        - 'Hey, ik ben Meander! Zelf heb ik ook mijn J&O tijd gehad, het was zo’n fijne en vertrouwde omgeving, dat wil ik daarom ook creëren voor de volgende generatie J&O’ers 😝!!'
```
dan past het net wat lekkerder op drie regels :)

2023-01-10 20:36 UTC, casperboone commented on sites/dwhdelft.nl/pages/jongenout.vue
> +        - 'Hey hey, mijn naam is Laurens ik vind het super fijn een plekje voor jonge lhbti personen, zoals ik dat ook had in mijn jeugd!'
Deze zin loopt niet helemaal lekker, copy paste foutje maybe?

2023-01-11 08:23 UTC, laurensWe commented
@casperboone na tinypng zijn sommige nog wel 100kb, is dat oke of nog verder scalen en weer tinypng'en?

2023-01-15 00:18 UTC, merged