feat: replace j&o team photo with new team
dwh-outsite/dwhdelft.nl pull request #543
Opened 2024-02-16 14:11 UTC by thomcsmits

2024-02-16 14:24 UTC, casperboone requested changes
The image is quite large in terms of dimensions and file size. Maybe try a smaller version of the original image and throw it through tinyjpg.com

2024-02-16 14:49 UTC, thomcsmits commented
> The image is quite large in terms of dimensions and file size. Maybe try a smaller version of the original image and throw it through tinyjpg.com

Thanks, done! Do we generally do this with all pictures? For performance?

2024-02-16 14:54 UTC, laurensWe approved these changes

2024-03-09 16:30 UTC, vanadie approved these changes

2024-03-09 16:49 UTC, merged