bugfix: positioning responsive icon
dwh-outsite/dwhdelft.nl pull request #637
Opened 2024-12-17 22:04 UTC by sharwinbobde

bufgfix for issue #635. Does this count as onboarding?

2024-12-17 22:20 UTC, sharwinbobde commented
🫦 
1.  ![image](https://github.com/user-attachments/assets/af03e1c0-bec9-44f1-9bcf-4577c5b19efc)
2.  ![image](https://github.com/user-attachments/assets/bfdfeb55-1b14-4c84-bced-44451ef6838b)
3.  ![image](https://github.com/user-attachments/assets/8e1daefd-6eab-4c3d-a8ab-9a4dc527984d)

2024-12-17 22:57 UTC, thomcsmits reviewed
Very nice! :) 

Can we add this to outsite.nl as well? 

[Here for fix1](https://github.com/dwh-outsite/dwhdelft.nl/blob/012086e23483441fa1e157d5213417d07069a3de/outsite.nl/components/pages/home/Intro.vue#L41)

[Here for fix2](https://github.com/dwh-outsite/dwhdelft.nl/blob/012086e23483441fa1e157d5213417d07069a3de/outsite.nl/pages/index.vue#L64)

2024-12-19 23:21 UTC, sharwinbobde commented
done.... but I saw something I can never unsee
![image](https://github.com/user-attachments/assets/5c0094d8-2ee6-47fc-91b5-2e56437e6b97)

2024-12-19 23:30 UTC, sharwinbobde commented
fixed the panda rotation:
![image](https://github.com/user-attachments/assets/86ef0f0c-364b-4cb7-bfc4-4dd0657f0af9)

2024-12-20 15:11 UTC, thomcsmits approved these changes
Nice! Good catch :)

2025-01-01 21:30 UTC, casperboone reviewed
Nice! Thx for the fixes

2025-01-01 21:30 UTC, casperboone commented on outsite.nl/pages/index.vue
> +        <Panda class="relative md:absolute bottom-0 left-5 w-full rotate-[12deg]" />
Instead of rotating the panda, I think it's better to fix the positioning for 430px-768px screens (not necessarily with such a specific target). Just to not change the visual appearance of the panda ;) 🐼

2025-01-03 11:15 UTC, sharwinbobde commented on outsite.nl/pages/index.vue
> +        <Panda class="relative md:absolute bottom-0 left-5 w-full rotate-[12deg]" />
Hey, I tried shifting the panda down before rotating it. It looked a bit odd, like just a stub peeking out. I wasn't happy with that, so I said just aligned the image with the diagonal stripe; it was more consistent, looked similar at all resolutions, and we see more of the panda. 

Ill try putting up a screenshot with the repositioned panda for comparison later today.

2025-01-04 11:55 UTC, thomcsmits requested changes
At this point, can you also add the same tweaks for the mixup site? Not yet incorporated in that PR as I wasn't sure what the rest would review

2025-01-04 12:01 UTC, casperboone commented
@thomcsmits i don’t think there’s anything to tweak on the mixup page. The surrounding components of the invite aren’t similar, so no relative spacing to set

2025-01-04 12:07 UTC, thomcsmits commented
What do you mean? It's the same icon position thing that would be fixed with 28px I believe
![image](https://github.com/user-attachments/assets/41fff77b-995b-40b1-99e9-1d5a0f174abf)

2025-01-04 12:09 UTC, casperboone commented
There are no changes to the icon position in this pr. Just the space surrounding the invite component

2025-01-04 12:11 UTC, thomcsmits commented
Didn't check it yet but I presumed the same changes would work if added to these 2 lines: 

https://github.com/dwh-outsite/dwhdelft.nl/blob/d42db48746238e15bc4471a1b4b85151d23ee228/dwhdelft.nl/pages/mixup.vue#L128

https://github.com/dwh-outsite/dwhdelft.nl/blob/d42db48746238e15bc4471a1b4b85151d23ee228/dwhdelft.nl/pages/mixup.vue#L114

2025-01-04 12:11 UTC, casperboone commented
Btw, the icon moving above the text on smaller screens is actually by design 😅 if that’s what you meant @thomcsmits

2025-01-04 12:12 UTC, thomcsmits commented
Ah well that was I think this entire PR😅, based on what I reported here: https://github.com/dwh-outsite/dwhdelft.nl/issues/635

2025-01-04 16:47 UTC, casperboone commented
Merging this for now because I want to do a big change to do the codebase. Let's tweak the panda stuff later 😄

2025-01-04 16:47 UTC, merged